### ISSUE TITLE
Bug: Parameters are listed as numbers in configuration

### ISSUE THREAD

**Issue by markusEmm123** [afkiwers/inventree_kicad#26]
In the configuration / parameter mapping the parameters are listed with their ID number and not with their name.

![image](https://github.com/afkiwers/inventree_kicad/assets/96077472/653f8e79-b7f5-4758-8bcf-728da681cdda)

**Comment by afkiwers** [comment]
That's an InvenTree issue.

**Comment by SchrodingersGat** [comment]
This will be addressed.in a future InvenTree release
