### ISSUE TITLE
Parts with ":" in their name cause KiCad to write out an invalid schematic file.

### ISSUE THREAD

**Issue by konkers** [afkiwers/inventree_kicad#38]
Repro steps:
1. Create an InvenTree part with a ":" in it's name.
2. Add that part to a KiCad schematic.
3. Save and close schematic.
4. Reopen schematic.
5. KiCad complains of an invalid character in symbol name.

I'm not sure of the correct fix for this.  The ":" could be remove or replaced with a "_" but that may, in rare cases, cause duplicate parts to be exported.  Alternately the part could not be exported from InvenTree and an error logged.  However, that could lead to confusion.

Attached is
1. Schematic with bad symbol name
2. Manually fixed schematic

[schematic_files.zip](https://github.com/afkiwers/inventree_kicad/files/13246533/schematic_files.zip)

**Comment by afkiwers** [comment]
That is actually a KiCad specific issue when it parses the schematic. Given how their library system is designed, colons are used as delimiters. So they can't be in the symbol/part name.

I guess we need some sort of action which either removes any colons, replaces them with white spaces or a different character.

![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/a50e3fd2-0523-4de6-8d93-caeb7144bcce)
![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/b67d277e-9cac-4ab0-b5ed-a4f750e9161d)
