### ISSUE TITLE
Default Symbol does not work

### ISSUE THREAD

**Issue by 30350n** [afkiwers/inventree_kicad#40]
Setting the Default Symbol for a category to `Device:R` does not work for me. This was probably broken by #39.
![image](https://github.com/afkiwers/inventree_kicad/assets/34186858/3509d45c-604a-452b-abe4-3a2705b57227)
![image](https://github.com/afkiwers/inventree_kicad/assets/34186858/db248708-3c25-461a-b5ca-456c38eca18a)

**Comment by afkiwers** [comment]
@30350n I created a fix for that. 

 Please update to version 1.3.2 and let me know if that resolves your issue.

**Comment by 30350n** [comment]
Will check once I'm done investigating the cause for the other issue I openend :)

**Comment by afkiwers** [comment]
It does if you run an earlier version but the latest should definitely support it.

It is working on my end
![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/b2126d0d-9247-46df-a15d-7637724afccb)

**Comment by 30350n** [comment]
Yep, works, thanks for the quick fix! :smiley:
