### ISSUE TITLE
Part URL is not fully qualified

### ISSUE THREAD

**Issue by 30350n** [afkiwers/inventree_kicad#41]
When creating a symbol in KiCad, the Part URL is not fully qualified.
![image](https://github.com/afkiwers/inventree_kicad/assets/34186858/9de18299-9875-480c-b566-4d2fff8a1155)
![image](https://github.com/afkiwers/inventree_kicad/assets/34186858/5be2ea4e-df33-4695-929f-22b17966bb39)

**Comment by 30350n** [comment]
(Currently investigating this, should hopefully be able to fix it myself ^^)

**Comment by afkiwers** [comment]
@30350n  what inventree version are you running? Would you be able past the full log?

**Comment by 30350n** [comment]
Master from a few commits ago, shouldn't really matter though.
The core issue seems to be that I simply don't have a `INVENTREE_BASE_URL` set. I'm wondering why [this](https://github.com/afkiwers/inventree_kicad/blob/main/inventree_kicad/serializers.py#L246) fallback isn't working though ...

**Comment by 30350n** [comment]
Aka: Why is there no request there?
