### ISSUE TITLE
BOM Import

### ISSUE THREAD

**Issue by SchrodingersGat** [afkiwers/inventree_kicad#53]
It would be handy now that this plugin has an XML importer to be able to directly import a BOM

**Comment by afkiwers** [comment]
I guess a simple select field somewhere could be used which contains all assemblies and is filterable. If something is selected, it would create a BOM. But what if there is already a bom?

![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/0171b9cc-647a-4a88-a1db-2615e50fd37a)

**Comment by SchrodingersGat** [comment]
> But what if there is already a bom?

As a starting point, could raise an exception if BOMItems exist, and the user has to clear out the BOM manually before uploading?

**Comment by tnemrap** [comment]
I am also interested of a function to create/update an bom on an assembly.

**Comment by afkiwers** [comment]
This feature is already available using InvenTree's BOM features.

I have been thinking about this the last couple of days and can't really see the benefits of having another way to create BOMs as importing BOMs using the BOM import tools from InvenTree are really working well; at least for me.

This being said, if anyone likes to make a pull request, go for it. 😉
