### ISSUE TITLE
Format README with column limit

### ISSUE THREAD

**Issue by 30350n** [afkiwers/inventree_kicad#65]
Making a separate issue for this:

The current README is written in a way were every paragraph just spans over a single line. This makes it really awkward to edit with an editor that doesn't have automatic wrapping enabled. I'd recommend to limit line length to a reasonable value like 100 or 80.

**Comment by afkiwers** [comment]
Addressed in: https://github.com/afkiwers/inventree_kicad/pull/44

**Comment by 30350n** [comment]
Actually, that wasn't addressed in #44 I reverted that change, I'll create another PR.
