### ISSUE TITLE
[FR]: Adding an option to control symbol visibility of IPN

### ISSUE THREAD

**Issue by JacobEFO** [afkiwers/inventree_kicad#80]
As of right now, if showing the IPN, it is set to invisible by default in the serializers.py:

```python
        if str2bool(self.plugin.get_setting('KICAD_INCLUDE_IPN', False)):
            fields['IPN'] = {
                'value': f'{part.IPN}',
                'visible': 'False'
            }
```

It would be a beneficial option to allow control of setting visibility. I am not entirely sure what the best way of controlling this, but a handle in the settings panel is one option.

**Comment by afkiwers** [comment]
addressed in https://github.com/afkiwers/inventree_kicad/pull/81
