### ISSUE TITLE
Question on using the plugin - where is footprint info stored?

### ISSUE THREAD

**Issue by StormTrooper** [afkiwers/inventree_kicad#96]
Been using KiCad and Inventree for a while now and just discovered this plugin which looks very useful. 

I've followed the installation document and managed to install the plugin (v1.4.1) with KiCad 8.0.2. 
Setup the API/categories etc and in the symbol library I can see the list of parts. 

So far so good. 

One thing I'm not following is where do you setup the symbol and footprint information for the part. 
I get the Inventree has no way to know what the symbol and footprint will be and this has to be manually entered for each part. 

![image](https://github.com/afkiwers/inventree_kicad/assets/1429043/2e4adf42-c880-4e61-8588-2cb18ecef08f)

Where do I do this though. I don't see anywhere in the part where this information can be entered?

![image](https://github.com/afkiwers/inventree_kicad/assets/1429043/c196c261-9109-44d3-bc47-975505cc37d9)

Am I correct in thinking the footprint info be stored in Inventree?

**Comment by afkiwers** [comment]
Hi @StormTrooper,

The plugin looks for parameters. An example below.
![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/00433f73-580b-48ed-a2c3-5a50fc4ad002)

You can define which parameters are used in several places. For a generic assignment you can use the plugin settings. Please note that there is a bug in inventree which means it won't display the name only the ID. If you click on it though it will show you the names.
![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/fb7de232-09b3-4b4e-907f-059aa336661c)

If you want to specify a specific value or footprint parameter for a certain category, you can do that inside the admin panel. This will override the generic plugin settings.
![image](https://github.com/afkiwers/inventree_kicad/assets/42826581/6476794d-1e44-4d14-a834-aeb9588ffc5d)

**Comment by StormTrooper** [comment]
Thanks for the details. That's the bit I was missing. 

Added the missing parameters to KiCad and then setup the plugin to use those parameters. 

Working perfectly now.

**Comment by StormTrooper** [comment]
@afkiwers  I thought I had it all working, but one thing that is confusing me. 

In Inventree I've for a part setup as follows:
![image](https://github.com/afkiwers/inventree_kicad/assets/1429043/baf6393a-1fb7-4bb2-af2a-ad0e674905b7)

When placing the part in KiCad I get the IPN | Value:

![image](https://github.com/afkiwers/inventree_kicad/assets/1429043/02747bc9-e933-4645-b7ec-ccb0bb0c04fb)

What do I need to change to just display the value. (100k)
Played around with a few settings but not having any luck.

**Comment by afkiwers** [comment]
Did you enable Include IPN in the settings? It looks like it's set to **include and show in schematic **

**Comment by StormTrooper** [comment]
![image](https://github.com/afkiwers/inventree_kicad/assets/1429043/e874d193-aa8a-4c10-b3d1-02d96c7b7f59)

![image](https://github.com/afkiwers/inventree_kicad/assets/1429043/5a1e842b-df1a-4737-ae0b-63d1c2b4e57f)

![image](https://github.com/afkiwers/inventree_kicad/assets/1429043/b5e066e0-6b23-4e37-b588-a96d8d76b2ff)

**Comment by afkiwers** [comment]
InvenTree is providing that to the plugin. Have a look under InvenTree settings->part->'Part Name Display Format' and play with that format. You probably have to get rid of some of the formatting.

Sorry, I don't have access to my computer at the moment just got my phone which makes it a bit harder to quickly check stuff on my side.

**Comment by afkiwers** [comment]
What's displayed as part name at the top in InvenTree when opening the parts page?

**Comment by StormTrooper** [comment]
Thanks, looks like it's the formatting.  If part.ipn exists then display it:

```{{ part.IPN if part.IPN }}{{ ' | ' if part.IPN }}{{ part.name }}{{ ' | ' if part.revision }}{{ part.revision if part.revision }}```

Same with revision. 

The part name is displayed as ```RES-100K-0805 | 100k``` in Inventree. 
I'll modify the formatting.

**Comment by StormTrooper** [comment]
Changed it to ```{{ part.name }}``` which fixes the issue. 

Made a note of the old setting in case something breaks down the line which expects that format.

**Comment by afkiwers** [comment]
Fantastic!

That's just a display thing and should not break anything.
